name: Convert Excel to JS Schedule

# Trigger on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  convert_excel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install xlsx

      - name: Run excel conversion
        run: node ./automation-scripts/excelToObject.js

      - name: Run json conversion
        run: node ./automation-scripts/jsonToObject.js

      - name: Run image list creation
        run: node ./automation-scripts/createImageList.js

      - name: Copy images to correct folder
        run: |
          rm -r ./public/images
          mkdir ./public/images
          cp ./config/images ./public/images

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./src/data
          git add ./public/images
          git commit -m "Automated update from config folder"
          git push
